# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 16 * * *'

jobs:
  pull_from_remote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set remote repo
    - run: git remote add ckan_official https://github.com/KSP-CKAN/CKAN-meta.git
    - name: Pull repo
    - run: git pull ckan_official main
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run script
      run: python ghproxy_replacer.py
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
